name: Feature Comment Trigger  

on:  
  issue_comment:  
    types: [created]  

jobs:  
  feature_comment:  
    if: startsWith(github.event.comment.body, 'feat:')  
    runs-on: ubuntu-latest  
    steps:  
      - name: Print feature comment  
        run: echo "Feature comment detected: '${{ github.event.comment.body }}'"  
        
      # Add more steps here for further actions when a comment is detected
