name: Commit Message Check  

on: [pull_request]  

jobs:  
  commit-check:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Check commit messages  
        run: |  
          git log --format=%s | grep -E '^(feat|fix|docs|style|refactor|perf|test|chore):'
