name: Commit Message Check  

on:  
  push:  
    branches:  
      - main  # Change this to your default branch if not main  

jobs:  
  commit-message:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v2  

      - name: Check Commit Message  
        run: |  
          # Get the latest commit message  
          latest_commit_message=$(git log -1 --pretty=%B)  
          
          # Check if the commit message starts with 'feat:'  
          if [[ ! $latest_commit_message =~ ^feat: ]]; then  
              echo "Error: Commit message must start with 'feat:'."  
              exit 1  
          fi
